name: Cron Test

on:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: |
          echo "Hello from GitHub Actions!"
          echo "Triggered at: $(date -u)"
